// Sign-in / account strings in English, Portuguese and Spanish.
// Placeholders like {name} are filled by t(key, { name }).
export const AUTH_STRINGS = {
  en: {
    email: 'Email',
    password: 'Password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    remember: 'Remember me on this device',
    forgot: 'Forgot password?',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    language: 'Language',
    loading: 'Loading…',
    forgotTitle: 'Reset your password',
    forgotIntro: "Enter your email and we'll send you a link to choose a new password.",
    sendLink: 'Send reset link',
    sending: 'Sending…',
    backToSignIn: 'Back to sign in',
    sentGeneric: "If that email exists, we've sent a password reset link to it.",
    noMailer: "Email delivery isn't set up on this server yet, so no message could be sent. Ask your administrator for the reset link.",
    resetTitle: 'Choose a new password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    setPassword: 'Set new password',
    saving: 'Saving…',
    pwMin: 'Password must be at least 8 characters.',
    pwMismatch: "Passwords don't match.",
    resetDone: 'Your password has been updated. You can sign in now.',
    resetNoToken: 'This reset link is incomplete. Request a new one from the sign-in page.',
    'err.invalid_credentials': 'Wrong email or password. Please try again.',
    'err.too_many_attempts': 'Too many attempts. Please wait a few minutes and try again.',
    'err.invalid_reset_link': 'This link is invalid or has expired. Request a new one.',
    'err.weak_password': 'Password must be at least 8 characters.',
    'err.wrong_current_password': 'Your current password is incorrect.',
    'err.same_password': 'The new password must be different from the current one.',
    'err.email_in_use': 'That email is already in use.',
    'err.invalid_email': 'Enter a valid email address.',
    'err.network': "Can't reach the server. Check your connection and try again.",
    'err.generic': 'Something went wrong. Please try again.',
    signOut: 'Sign out',
    accountTitle: 'My account',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    passwordChanged: 'Password updated.',
    mustChange: 'Please choose a new password to continue.',
    owner: 'Owner',
    staff: 'Staff',
    staffTitle: 'Login accounts',
    staffSub: 'People who can sign in to {app}',
    addStaff: 'Add staff member',
    name: 'Name',
    tempPassword: 'Temporary password',
    tempPasswordHint: 'At least 8 characters. They will be asked to change it the first time they sign in.',
    createAccount: 'Create account',
    creating: 'Creating…',
    accountCreated: 'Account created. Share the email and temporary password with them.',
    remove: 'Remove',
    removeConfirm: 'Remove {name}? They will no longer be able to sign in.',
    setTemp: 'New temporary password',
    tempSet: 'Temporary password set.',
    cancel: 'Cancel',
    you: 'you',
    legalBack: 'Back',
    lastUpdated: 'Last Updated',
    termsTitle: 'Terms of Service',
    privacyTitle: 'Privacy Policy',
  },
  pt: {
    email: 'E-mail',
    password: 'Senha',
    showPassword: 'Mostrar senha',
    hidePassword: 'Ocultar senha',
    remember: 'Lembrar de mim neste dispositivo',
    forgot: 'Esqueceu a senha?',
    signIn: 'Entrar',
    signingIn: 'Entrando…',
    terms: 'Termos de Uso',
    privacy: 'Política de Privacidade',
    language: 'Idioma',
    loading: 'Carregando…',
    forgotTitle: 'Redefinir sua senha',
    forgotIntro: 'Digite seu e-mail e enviaremos um link para você escolher uma nova senha.',
    sendLink: 'Enviar link',
    sending: 'Enviando…',
    backToSignIn: 'Voltar para o login',
    sentGeneric: 'Se esse e-mail existir, enviamos um link para redefinir a senha.',
    noMailer: 'O envio de e-mail ainda não está configurado neste servidor, então nenhuma mensagem foi enviada. Peça o link ao administrador.',
    resetTitle: 'Escolha uma nova senha',
    newPassword: 'Nova senha',
    confirmPassword: 'Confirmar nova senha',
    setPassword: 'Definir nova senha',
    saving: 'Salvando…',
    pwMin: 'A senha precisa ter pelo menos 8 caracteres.',
    pwMismatch: 'As senhas não são iguais.',
    resetDone: 'Sua senha foi atualizada. Agora você já pode entrar.',
    resetNoToken: 'Este link está incompleto. Peça um novo na tela de login.',
    'err.invalid_credentials': 'E-mail ou senha incorretos. Tente de novo.',
    'err.too_many_attempts': 'Muitas tentativas. Aguarde alguns minutos e tente de novo.',
    'err.invalid_reset_link': 'Este link é inválido ou expirou. Peça um novo.',
    'err.weak_password': 'A senha precisa ter pelo menos 8 caracteres.',
    'err.wrong_current_password': 'A senha atual está incorreta.',
    'err.same_password': 'A nova senha precisa ser diferente da atual.',
    'err.email_in_use': 'Esse e-mail já está em uso.',
    'err.invalid_email': 'Digite um e-mail válido.',
    'err.network': 'Não foi possível falar com o servidor. Verifique a conexão e tente de novo.',
    'err.generic': 'Algo deu errado. Tente de novo.',
    signOut: 'Sair',
    accountTitle: 'Minha conta',
    changePassword: 'Trocar senha',
    currentPassword: 'Senha atual',
    passwordChanged: 'Senha atualizada.',
    mustChange: 'Escolha uma nova senha para continuar.',
    owner: 'Dono',
    staff: 'Equipe',
    staffTitle: 'Contas de acesso',
    staffSub: 'Pessoas que podem entrar no {app}',
    addStaff: 'Adicionar membro da equipe',
    name: 'Nome',
    tempPassword: 'Senha temporária',
    tempPasswordHint: 'Pelo menos 8 caracteres. A pessoa precisará trocá-la no primeiro acesso.',
    createAccount: 'Criar conta',
    creating: 'Criando…',
    accountCreated: 'Conta criada. Passe o e-mail e a senha temporária para a pessoa.',
    remove: 'Remover',
    removeConfirm: 'Remover {name}? A pessoa não poderá mais entrar.',
    setTemp: 'Nova senha temporária',
    tempSet: 'Senha temporária definida.',
    cancel: 'Cancelar',
    you: 'você',
    legalBack: 'Voltar',
    lastUpdated: 'Última atualização',
    termsTitle: 'Termos de Uso',
    privacyTitle: 'Política de Privacidade',
  },
  es: {
    email: 'Correo electrónico',
    password: 'Contraseña',
    showPassword: 'Mostrar contraseña',
    hidePassword: 'Ocultar contraseña',
    remember: 'Recordarme en este dispositivo',
    forgot: '¿Olvidaste tu contraseña?',
    signIn: 'Iniciar sesión',
    signingIn: 'Entrando…',
    terms: 'Términos de Servicio',
    privacy: 'Política de Privacidad',
    language: 'Idioma',
    loading: 'Cargando…',
    forgotTitle: 'Restablecer tu contraseña',
    forgotIntro: 'Escribe tu correo y te enviaremos un enlace para elegir una nueva contraseña.',
    sendLink: 'Enviar enlace',
    sending: 'Enviando…',
    backToSignIn: 'Volver al inicio de sesión',
    sentGeneric: 'Si ese correo existe, te enviamos un enlace para restablecer la contraseña.',
    noMailer: 'El envío de correo aún no está configurado en este servidor, así que no se envió ningún mensaje. Pide el enlace al administrador.',
    resetTitle: 'Elige una nueva contraseña',
    newPassword: 'Nueva contraseña',
    confirmPassword: 'Confirmar nueva contraseña',
    setPassword: 'Guardar nueva contraseña',
    saving: 'Guardando…',
    pwMin: 'La contraseña debe tener al menos 8 caracteres.',
    pwMismatch: 'Las contraseñas no coinciden.',
    resetDone: 'Tu contraseña se actualizó. Ya puedes iniciar sesión.',
    resetNoToken: 'Este enlace está incompleto. Pide uno nuevo en la pantalla de inicio de sesión.',
    'err.invalid_credentials': 'Correo o contraseña incorrectos. Inténtalo de nuevo.',
    'err.too_many_attempts': 'Demasiados intentos. Espera unos minutos e inténtalo de nuevo.',
    'err.invalid_reset_link': 'Este enlace no es válido o expiró. Pide uno nuevo.',
    'err.weak_password': 'La contraseña debe tener al menos 8 caracteres.',
    'err.wrong_current_password': 'La contraseña actual es incorrecta.',
    'err.same_password': 'La nueva contraseña debe ser distinta de la actual.',
    'err.email_in_use': 'Ese correo ya está en uso.',
    'err.invalid_email': 'Escribe un correo válido.',
    'err.network': 'No se puede conectar con el servidor. Revisa tu conexión e inténtalo de nuevo.',
    'err.generic': 'Algo salió mal. Inténtalo de nuevo.',
    signOut: 'Cerrar sesión',
    accountTitle: 'Mi cuenta',
    changePassword: 'Cambiar contraseña',
    currentPassword: 'Contraseña actual',
    passwordChanged: 'Contraseña actualizada.',
    mustChange: 'Elige una nueva contraseña para continuar.',
    owner: 'Propietario',
    staff: 'Equipo',
    staffTitle: 'Cuentas de acceso',
    staffSub: 'Personas que pueden entrar a {app}',
    addStaff: 'Agregar miembro del equipo',
    name: 'Nombre',
    tempPassword: 'Contraseña temporal',
    tempPasswordHint: 'Al menos 8 caracteres. Se le pedirá cambiarla la primera vez que entre.',
    createAccount: 'Crear cuenta',
    creating: 'Creando…',
    accountCreated: 'Cuenta creada. Comparte el correo y la contraseña temporal con la persona.',
    remove: 'Quitar',
    removeConfirm: '¿Quitar a {name}? Ya no podrá iniciar sesión.',
    setTemp: 'Nueva contraseña temporal',
    tempSet: 'Contraseña temporal establecida.',
    cancel: 'Cancelar',
    you: 'tú',
    legalBack: 'Volver',
    lastUpdated: 'Última actualización',
    termsTitle: 'Términos de Servicio',
    privacyTitle: 'Política de Privacidad',
  },
};
